### ISSUE TITLE
Advanced Filtering

### ISSUE THREAD

**Issue by depuits** [akmolina28/last-watch-ai#4]
What does the `Smart filter` do and how does the `Mask File` work?

**Comment by akmolina28** [comment]
Use smart filter if you want to ignore objects that are not moving like a parked car. It looks at the previous event to see if the object was in a similar position. The precision is a percentage of how much the subsequent objects need to overlap.

Use masking if you have an area that you always want to ignore like a public street. You have to create a mask file and upload it. The mask file is an image file with the same resolution as your camera feed, and any areas filled in will be masked. If more than half of the person/car/whatever is behind the mask, it will be ignored.

I like to use Gimp or any other editor that can do layers. I take a snapshot from the camera and draw the mask over it in a new layer, then save only the mask layer as a png and upload it. Its good to give it some transparency as well so you can see through it in the interface later.

**Comment by depuits** [comment]
Okay the smart filter is a really nice feature.

If i understand correctly any areas that are not completely transparent are ignored by mask? So it's not a black and white mask and the color doesn't really matter.

**Comment by akmolina28** [comment]
Yes that's right. It looks at the alpha channel of each pixel to determine if that x/y coordinate is masked. As long as the opacity is above 20% or so it should work regardless of color.
