### ISSUE TITLE
No image display on web interface.

### ISSUE THREAD

**Issue by lsawyer3** [akmolina28/last-watch-ai#45]
Can't seem to figure out why I don't get the image displayed on the web interface. It is just blank. Everything else seems to work fine.  Also it generates a bunch of console errors in Chrome. That all look like this....

app.js?id=1d007da1358979320604:2 Uncaught DOMException: Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The HTMLImageElement provided is in the 'broken' state.
    at h.Image._draw (http://192.168.1.176:8080/js/app.js?id=1d007da1358979320604:2:2347029)
    at h.renderWithContext (http://192.168.1.176:8080/js/app.js?id=1d007da1358979320604:2:2337108)
    at h.Image.h.Entity.draw (http://192.168.1.176:8080/js/app.js?id=1d007da1358979320604:2:2341057)
    at h.addToStage (http://192.168.1.176:8080/js/app.js?id=1d007da1358979320604:2:2336043)
    at h._callback (http://192.168.1.176:8080/js/app.js?id=1d007da1358979320604:2:2099528)
    at h._animate (http://192.168.1.176:8080/js/app.js?id=1d007da1358979320604:2:2338182)

Thanks!

![image](https://user-images.githubusercontent.com/32366656/107886141-a1f81400-6ec3-11eb-9eba-d27443bfde87.png)

**Comment by akmolina28** [comment]
This is either a file permissions issue or an issue with the symlink. It looks like it generated predictions, so it was able to access the image file. I have seen this issue before so I think I can help you fix it.

A few questions:

* What OS is this running on?
* What is your docker version?
* Please share your .env file

**Comment by lsawyer3** [comment]
Thank you!  Windows 10 , docker 20.10.2, and my .env file looks like:

WATCH_FOLDER=D:\BlueIris\aiimput
WEB_INTERFACE_URL=http://192.168.1.176
WEB_INTERFACE_PORT=8080

# How many days to keep in database (0 for unlimited)
DATA_RETENTION_DAYS=7

# Set to true if the watcher is not picking up new image files quickly.
# Unusual watch folders like network shares may require polling.
WATCH_USE_POLLING=false

# Sets the PID and GID of the web server user so that it can access
# the source files.
# Change these to match your user ID. Run 'echo $UID' to get your ID.
# On Windows this setting does not matter.
USER_ID=1000
GROUP_ID=1000

# Turn on debugging to troubleshoot errors
APP_DEBUG=true

# Change the Deepstack base url if you are hosting deepstack outside of docker.
DEEPSTACK_BASE_URL=http://deepstack:5000/

**Comment by akmolina28** [comment]
Try deleting the symlink and recreating it. The symlink is how the system maps images from your watch folder into the web app.

```
cd /path/to/last-watch-ai

rm src/public/storage

docker-compose run --rm artisan storage:link
```

You should get some output like "The links have been created". After that, try refreshing the detection event page again.

**Comment by lsawyer3** [comment]
That fixed it. Thanks for your help.

**Comment by akmolina28** [comment]
Great, enjoy!

By the way, you might have to repeat this process if you ever change your watch folder.
