### ISSUE TITLE
No processing?

### ISSUE THREAD

**Issue by andrepintorj** [akmolina28/last-watch-ai#59]
Hi Andrew, I'm continuing my quest on running this on my Mac... The good news is that I see it consuming images and counting them on the UI as images processed... The bad news is that looks like the app is not sending requests to deepstack because I don't see any processing results on "deepstack logs" and nothing shows on "error logs" either :(

Any luck/suggestion on how to debug this?

**Comment by akmolina28** [comment]
1. Did you create a detection profile which matches the image file name? Deepstack will not be called unless the image file matches at least one of the profiles.

2. Do you see the image thumbnails in the deteciton events list? Can you click the event to get into the detection event screen? What do you see there?

3. Assuming you have a matching profile set up, and assuming the web server is storing the images correctly, then there may indeed be an issue with calling deepstack. You can check http://localhost:5001 to see if the deepstack service is running. 

If the service is indeed running, then there may be some difference in how docker names the service on mac OS. On windows and linux, the container is named using the service name which is "deepstack" in this case. The deepstack service url is configured in the env file so you can change it, but I think this is not likely to be the problem. By default, the address should be http://deepstack:5000/.

4. You can check the log file at src/storage/logs/laravel.log to see if any exceptions are logged.

**Comment by andrepintorj** [comment]
So, yes... I created the profile with matching filename pattern. Deepstack is running fine and I see image thumbnails being shown on the app but looks like they are not being "processed" by deepstack.

Laravel log is displaying some issues connecting to mysql, I now will investigate more on this. Let me see what I will discover next.

```
[2021-03-25 17:41:18] production.ERROR: SQLSTATE[HY000] [2002] Connection refused {"exception":"[object] (PDOException(code: 2002): SQLSTATE[HY000] [2002] Connection refused at /var/www/app/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php:70)
[stacktrace]
#0 /var/www/app/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php(70): PDO->__construct('mysql:host=127....', 'forge', '', Array)
```

**Comment by akmolina28** [comment]
Those kinds of errors can happen when the containers are first starting up. Most likely something was trying to call mysql before the container was up and running. It looks like that error was logged a few days ago, so you can ignore that unless you see it continuing to happen.

**Comment by akmolina28** [comment]
Can you go to the detection event page and confirm that the pattern matching worked? From the events list you can click on the event to view the details, and you should see the list of profiles which were matched.

![image](https://user-images.githubusercontent.com/2997206/112864435-6b461980-907d-11eb-9128-43f56b724cbb.png)

**Comment by andrepintorj** [comment]
so, with this screenshot you helped me find that the issue was on the pattern matching. Looks like my pattern was incorrect making it "bypass"the files. I'll probably fork and propose some OSX PRs with my findings. But yes: this works on a Mac! :)

**Comment by akmolina28** [comment]
Excellent! I will think about some adding discovery mechanisms to make it more obvious when an event did not match any profiles.
