### ISSUE TITLE
Upgrading loses settings and data

### ISSUE THREAD

**Issue by depuits** [akmolina28/last-watch-ai#6]
I'm probably doing something wrong but whenever I upgrade to a new version I lose all the data and configuration in the app. These are the steps I use to upgrade on linux/debian:

```
# stop the current app
cd last-watch-ai
sudo docker-compose down

cd ..

# move old install
mv last-watch-ai last-watch-ai-old

# download new version
curl -s https://api.github.com/repos/akmolina28/last-watch-ai/releases/latest \
| grep "browser_download_url" \
| cut -d : -f 2,3 \
| tr -d \" \
| wget -qi - -O - > last-watch-ai-latest.zip

unzip -q last-watch-ai-latest.zip -d .

# copy previous config file
cp last-watch-ai-old/.env last-watch-ai/.env

# copy sql data
sudo cp -R last-watch-ai-old/mysql last-watch-ai/mysql

cd last-watch-ai

sudo chown -R www-data:www-data src
sudo find src -type f -exec chmod 644 {} \;
sudo find src -type d -exec chmod 755 {} \;

# run migration
sudo docker-compose run --rm artisan migrate

#start the program
sudo docker-compose up -d --build site

sudo docker exec -it lw_php rm /var/www/app/public/storage
sudo docker exec -it lw_php php artisan storage:link

# remove old files
sudo rm -rf ../last-watch-ai-old
```

Or as a [gist](https://gist.github.com/depuits/115b35515f753e9d634e1457307f0d66)

**Comment by akmolina28** [comment]
You might have to remove the mysql folder from the destination before copying it over.

I just finished the official install guide for Ubuntu and I actually have a step to remove the mysql folder first. See here: https://kleypot.com/last-watch-ai-ubuntu-installation-and-upgrading/

With that said, I would actually recommend installing from source. It makes future updates *much* easier. You can still recover your data if you install from source. You would just have to copy over these three things before building the code:

1. .env file
2. mysql folder (completely remove the mysql folder from the destination first)
3. your mask files, if you have any. they are in ./src/storage/app/public/masks

So you would just follow the steps in the install guide, except you would migrate your old data right after step 1.

**Comment by depuits** [comment]
I'm guessing that there won't be an issue when upgrading using the source because no data needs to be moved. Using the steps you've describe kept the data when migrating from release to the source build.

**Comment by akmolina28** [comment]
> I'm guessing that there won't be an issue when upgrading using the source because no data needs to be moved. Using the steps you've describe kept the data when migrating from release to the source build.

That's right. From now on you can upgrade by pulling the source code from git and rebuilding it. There won't be a need to make a new install folder, move your data over, set permissions, etc. All of your data and settings will stay put.
