### ISSUE TITLE
Substitution Variables section in WebRequest is out of date

### ISSUE THREAD

**Issue by davidacampos** [akmolina28/last-watch-ai#63]
In UI defined here: https://github.com/akmolina28/last-watch-ai/blob/8bf28dc7b18aa37fed0127c0ad67fb18b0f84d5a/src/resources/js/components/WebRequestConfigs.vue#L56 there are missing several supported substitutions defined in: https://github.com/akmolina28/last-watch-ai/blob/8bf28dc7b18aa37fed0127c0ad67fb18b0f84d5a/src/app/PayloadHelper.php#L7

I tried %image_url%, even if it was not specified in the UI, and it worked as expected.

**Comment by davidacampos** [comment]
Also, it would be great if we could replace to the thumbnail URL directly, instead of having to get the event ID, call, the API, then get the thumbnail image... same might apply to the image itself, as it seems the /api/events/{ID}/img is fairly slow compared to just pulling /storage/events/{GUID}.jpeg (understandable, as it's calling the DB and what not).

**Comment by davidacampos** [comment]
On second though... another solution might be that instead of having randomly generated GUID used within /storage/events/GUID.jpeg, maybe using some simple hashing like MD5 or so based on the original file name (i.e. %image_file_name%), that way no need to call the API to get the storage location, as long as you already have the original filename

**Comment by davidacampos** [comment]
For anyone interested, for the comment above (about been able to get the direct image link, instead of a link that tries to "download" the image), I made a minor change in my local PayloadHelper.php and it's working great. I just added the following line before the "return $replaced;":

`$replaced = str_replace('%image_path%', $event->imageFile->getPath(), $replaced);`

This works great for my use case which is BI sending alert images to Last-Watch-AI, which then triggers a web-hook that triggers a push notification to a PWA. When the user clicks on the PWA's notification is a direct link to the Last-Watch_AI image that triggered the event. This is way faster than the /api/events/{ID}/img call

**Comment by akmolina28** [comment]
I actually have some changes in the dev branch to clean up the substitution variables and standardize them across the different automation types. The substitution code was pretty rushed so I'm not surprised that you found some gaps there. I'll see about adding some variables for direct jpg links for the event and the thumbnail rather than the resource url.

**Comment by akmolina28** [comment]
See acb73d2bfaf914dd48fd55247ad60958f76cb4cf

I had already fixed the issues you described but I've been busy the last few weeks and haven't released it. Web request substitutions are fixed and tested, but I started adding substitutions for MQTT automations and I haven't written those tests yet. Once I write the tests for MQTT I'll do a new release. Until then you can pull dev if you want. I actually use the dev branch for my home automation and everything has been working fine.

**Comment by davidacampos** [comment]
This is great, will pull the dev branch. Thanks!
