### ISSUE TITLE
Passing additional variables via HA API body

### ISSUE THREAD

**Issue by djshubs** [akmolina28/last-watch-ai#70]
Hello! 

Thank you for creating this awesome project. I'm getting errors when I'm trying to pass additional values to HA API based on the documentation from HA. 

Below is the body: 

```
{
	"state": "on", 	
        "unique_id": "garage_ext_activity",
	"name": "Activity outside Garage",
	"attributes": {
 		"object_classes": %object_classes%, 
 		"event_url": %event_url%,
 		"image_download_link": %image_download_link%
	}
}
```

However, I keep getting the following errors:

Automation Type | Event | Error | Occurred At
-- | -- | -- | --
web_request | 192.168.200.3_01_20220201102441030_MOTION_DETECTION.jpg | Argument 3 passed to App\WebRequestConfig::postRequest() must be of the type array, null given, called in /var/www/app/app/WebRequestConfig.php on line 75 | 2 hours ago

What am I missing here?

**Comment by akmolina28** [comment]
Check you json syntax. You probably need quotes around the variables.
